# Generated by Django 5.0.2 on 2024-05-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Car Make',
                'verbose_name_plural': 'Car Makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Car Spec',
                'verbose_name_plural': 'Car Specs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Car_Management.carmake')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_begin', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='Car_Management.carmodel')),
            ],
            options={
                'verbose_name': 'Car Generation',
                'verbose_name_plural': 'Car Generations',
                'ordering': ['model', 'year_begin'],
            },
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Car_Management.cargeneration')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Car_Management.carmodel')),
            ],
            options={
                'verbose_name': 'Car Serie',
                'verbose_name_plural': 'Car Series',
                'ordering': ['model', 'generation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='Car_Management.carspec')),
            ],
            options={
                'verbose_name': 'Car Spec Value',
                'verbose_name_plural': 'Car Spec Values',
                'ordering': ['trim', 'spec'],
            },
        ),
        migrations.AddField(
            model_name='carspec',
            name='spec_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='Car_Management.carspecvalue'),
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_production_year', models.PositiveIntegerField()),
                ('end_production_year', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='Car_Management.carmodel')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='Car_Management.carserie')),
            ],
            options={
                'verbose_name': 'Car Trim',
                'verbose_name_plural': 'Car Trims',
                'ordering': ['model', 'serie', 'start_production_year'],
            },
        ),
        migrations.AddField(
            model_name='carspecvalue',
            name='trim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='Car_Management.cartrim'),
        ),
    ]
