# Generated by Django 5.0.2 on 2024-06-05 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Car Make',
                'verbose_name_plural': 'Car Makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Car_Management.carmake')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year_begin', models.CharField(blank=True, max_length=200, null=True)),
                ('year_end', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='Car_Management.carmodel')),
            ],
            options={
                'verbose_name': 'Car Generation',
                'verbose_name_plural': 'Car Generations',
                'ordering': ['model', 'year_begin'],
            },
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Car_Management.cargeneration')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Car_Management.carmodel')),
            ],
            options={
                'verbose_name': 'Car Serie',
                'verbose_name_plural': 'Car Series',
                'ordering': ['model', 'generation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_production_year', models.CharField(blank=True, max_length=200, null=True)),
                ('end_production_year', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='Car_Management.carmodel')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='Car_Management.carserie')),
            ],
            options={
                'verbose_name': 'Car Trim',
                'verbose_name_plural': 'Car Trims',
                'ordering': ['model', 'serie', 'start_production_year'],
            },
        ),
        migrations.CreateModel(
            name='CarSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('spec_name', models.CharField(max_length=200)),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='Car_Management.cartrim')),
            ],
            options={
                'verbose_name': 'Car Spec',
                'verbose_name_plural': 'Car Specs',
                'ordering': ['trim'],
            },
        ),
    ]
