# Generated by Django 5.0.6 on 2024-06-14 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Car Make',
                'verbose_name_plural': 'Car Makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Car_Management.carmake')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year_begin', models.CharField(blank=True, max_length=200, null=True)),
                ('year_end', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='Car_Management.carmodel')),
            ],
            options={
                'verbose_name': 'Car Generation',
                'verbose_name_plural': 'Car Generations',
                'ordering': ['model', 'year_begin'],
            },
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Car_Management.cargeneration')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Car_Management.carmodel')),
            ],
            options={
                'verbose_name': 'Car Serie',
                'verbose_name_plural': 'Car Series',
                'ordering': ['model', 'generation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_production_year', models.CharField(blank=True, max_length=200, null=True)),
                ('end_production_year', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='Car_Management.carmodel')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='Car_Management.carserie')),
            ],
            options={
                'verbose_name': 'Car Trim',
                'verbose_name_plural': 'Car Trims',
                'ordering': ['model', 'serie', 'start_production_year'],
            },
        ),
        migrations.CreateModel(
            name='CarSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('spec_name', models.CharField(blank=True, max_length=200, null=True)),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='Car_Management.cartrim')),
            ],
            options={
                'verbose_name': 'Car Spec',
                'verbose_name_plural': 'Car Specs',
                'ordering': ['trim'],
            },
        ),
        migrations.CreateModel(
            name='UserCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('oc_date', models.DateField(blank=True, null=True)),
                ('tech_date', models.DateField(blank=True, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='static/usr/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('refuel', 'Tankowanie'), ('repair', 'Naprawa')], max_length=50)),
                ('report_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/usr/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Car_Management.usercars')),
            ],
        ),
    ]
