# Generated by Django 5.0.2 on 2024-06-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspec',
            name='spec_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
