# Generated by Django 5.0.2 on 2024-06-13 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Management', '0002_alter_carspec_spec_name_alter_carspec_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('registration', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('oc_date', models.DateField(blank=True, null=True)),
                ('tech_date', models.DateField(blank=True, null=True)),
                ('car_image', models.ImageField(upload_to='car_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('oc_date', models.DateField(blank=True, null=True)),
                ('tech_date', models.DateField(blank=True, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
