# Generated by Django 5.0.2 on 2024-06-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Management', '0004_delete_usercar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='usercars',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Management.carmake'),
        ),
        migrations.AlterField(
            model_name='usercars',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Management.carmodel'),
        ),
    ]
