# Generated by Django 5.0.2 on 2024-06-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Management', '0005_alter_usercars_car_image_alter_usercars_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercars',
            name='car_make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercars',
            name='car_model',
            field=models.CharField(max_length=100),
        ),
    ]
