# Generated by Django 5.0.2 on 2024-06-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Management', '0007_userreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreports',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Car_Management.usercars'),
            preserve_default=False,
        ),
    ]
