# Generated by Django 5.0.2 on 2024-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Management', '0008_userreports_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/usr/'),
        ),
        migrations.AlterField(
            model_name='userreports',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/usr/'),
        ),
    ]
