# Generated by Django 5.0.2 on 2024-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Management', '0010_userreports_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreports',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
